version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Exposes port 80 from the container to port 3000 on your local machine
    environment:
      - NODE_ENV=production
      - VITE_API_KEY= #Define your api keys heres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
